import axios from "axios";

const API_URL = "https://your-api-endpoint/events"; // Replace with your actual API URL
const events = [
  {
    name: "Event One",
    by: "ajdih",
    area: "Lower Manhattan",
    day: "Monday",
    date: "Nov,13 2023",
    scheduledTime: "10:00 AM - 11:00 PM",
    image:
      "https://images.unsplash.com/photo-1492684223066-81342ee5ff30?q=80&w=1170&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
    details:
      "Details for Event OneDetails forDetails forDetails forDetails forDetails forDetails forDetails forDetails forDetails forDetails for",
    price: "25.99",
    ticketsLeft: "100",
    address: "123 Main St, Anytown, CA",
    questions: [
      {
        number: 1,
        question: "Company/Organization:",
        type: "input",
        answer: "",
        multipleAllowed: false,
        options: [],
      },
      {
        number: 2,
        question: "Job Title:",
        type: "input",
        answer: "",
        multipleAllowed: false,
        options: [],
      },
      {
        number: 2,
        question: "Are you a student?",
        type: "options",
        answer: "",
        multipleAllowed: false,
        options: ["Yes", "No"],
      },
      {
        number: 2,
        question: "Where did you hear about this event?",
        type: "options",
        answer: "",
        multipleAllowed: true,
        options: ["Linkedin", "Facebook", "Twitter", "Instagram"],
      },
    ],
  },
  {
    name: "Event Two",
    by: "ajdih",
    area: "Lower Manhattan",
    day: "Monday",
    date: "Nov,13 2023",
    scheduledTime: "10:00 AM - 11:00 PM",
    image:
      "https://images.unsplash.com/photo-1492684223066-81342ee5ff30?q=80&w=1170&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
    details:
      "Details for Event TwoDetails forDetails forDetails forDetails forDetails forDetails forDetails forDetails forDetails forDetails for",
    price: "19.95",
    ticketsLeft: "50",
    address: "456 Elm St, Anytown, CA",
    questions: [
      {
        number: 1,
        question: "Company/Organization:",
        type: "input",
        answer: "",
        multipleAllowed: false,
        options: [],
      },
      {
        number: 2,
        question: "Job Title:",
        type: "input",
        answer: "",
        multipleAllowed: false,
        options: [],
      },
      {
        number: 2,
        question: "Are you a student?",
        type: "options",
        answer: "",
        multipleAllowed: false,
        options: ["Yes", "No"],
      },
      {
        number: 2,
        question: "Where did you hear about this event?",
        type: "options",
        answer: "",
        multipleAllowed: true,
        options: ["Linkedin", "Facebook", "Twitter", "Instagram"],
      },
    ],
  },
  {
    name: "Event Three",
    by: "ajdih",
    area: "Lower Manhattan",
    day: "Monday",
    date: "Nov,13 2023",
    scheduledTime: "10:00 AM - 11:00 PM",
    image:
      "https://images.unsplash.com/photo-1492684223066-81342ee5ff30?q=80&w=1170&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
    details:
      "Details for Event ThreeDetails forDetails forDetails forDetails forDetails forDetails forDetails forDetails forDetails for",
    price: "39.99",
    ticketsLeft: "20",
    address: "789 Oak St, Anytown, CA",
    questions: [
      {
        number: 1,
        question: "Company/Organization:",
        type: "input",
        answer: "",
        multipleAllowed: false,
        options: [],
      },
      {
        number: 2,
        question: "Job Title:",
        type: "input",
        answer: "",
        multipleAllowed: false,
        options: [],
      },
      {
        number: 2,
        question: "Are you a student?",
        type: "options",
        answer: "",
        multipleAllowed: false,
        options: ["Yes", "No"],
      },
      {
        number: 2,
        question: "Where did you hear about this event?",
        type: "options",
        answer: "",
        multipleAllowed: true,
        options: ["Linkedin", "Facebook", "Twitter", "Instagram"],
      },
    ],
  },
  {
    name: "Event Four",
    by: "ajdih",
    area: "Lower Manhattan",
    day: "Monday",
    date: "Nov,13 2023",
    scheduledTime: "10:00 AM - 11:00 PM",
    image:
      "https://images.unsplash.com/photo-1492684223066-81342ee5ff30?q=80&w=1170&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
    details:
      "Details for Event FourDetails forDetails forDetails forDetails forDetails forDetails forDetails forDetails for",
    price: "15.00",
    ticketsLeft: "Unlimited",
    address: "1011 Pine St, Anytown, CA",
    questions: [
      {
        number: 1,
        question: "Company/Organization:",
        type: "input",
        answer: "",
        multipleAllowed: false,
        options: [],
      },
      {
        number: 2,
        question: "Job Title:",
        type: "input",
        answer: "",
        multipleAllowed: false,
        options: [],
      },
      {
        number: 2,
        question: "Are you a student?",
        type: "options",
        answer: "",
        multipleAllowed: false,
        options: ["Yes", "No"],
      },
      {
        number: 2,
        question: "Where did you hear about this event?",
        type: "options",
        answer: "",
        multipleAllowed: true,
        options: ["Linkedin", "Facebook", "Twitter", "Instagram"],
      },
    ],
  },
  {
    name: "Event Five",
    by: "ajdih",
    area: "Lower Manhattan",
    day: "Monday",
    date: "Nov,13 2023",
    scheduledTime: "10:00 AM - 11:00 PM",
    image:
      "https://images.unsplash.com/photo-1492684223066-81342ee5ff30?q=80&w=1170&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
    details:
      "Details for Event FiveDetails forDetails forDetails forDetails forDetails forDetails forDetails forDetails forDetails forDetails for",
    price: "Free",
    ticketsLeft: "N/A",
    address: "1234 Maple St, Anytown, CA",
    questions: [
      {
        number: 1,
        question: "Company/Organization:",
        type: "input",
        answer: "",
        multipleAllowed: false,
        options: [],
      },
      {
        number: 2,
        question: "Job Title:",
        type: "input",
        answer: "",
        multipleAllowed: false,
        options: [],
      },
      {
        number: 2,
        question: "Are you a student?",
        type: "options",
        answer: "",
        multipleAllowed: false,
        options: ["Yes", "No"],
      },
      {
        number: 2,
        question: "Where did you hear about this event?",
        type: "options",
        answer: "",
        multipleAllowed: true,
        options: ["Linkedin", "Facebook", "Twitter", "Instagram"],
      },
    ],
  },
  {
    name: "Event Six",
    by: "ajdih",
    area: "Lower Manhattan",
    day: "Monday",
    date: "Nov,13 2023",
    scheduledTime: "10:00 AM - 11:00 PM",
    image:
      "https://images.unsplash.com/photo-1492684223066-81342ee5ff30?q=80&w=1170&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
    details:
      "Details for Event SixDetails forDetails forDetails forDetails forDetails forDetails forDetails forDetails forDetails forDetails forDetails for",
    price: "49.50",
    ticketsLeft: "75",
    address: "5678 Beach Blvd, Anytown, CA",
    questions: [
      {
        number: 1,
        question: "Company/Organization:",
        type: "input",
        answer: "",
        multipleAllowed: false,
        options: [],
      },
      {
        number: 2,
        question: "Job Title:",
        type: "input",
        answer: "",
        multipleAllowed: false,
        options: [],
      },
      {
        number: 2,
        question: "Are you a student?",
        type: "options",
        answer: "",
        multipleAllowed: false,
        options: ["Yes", "No"],
      },
      {
        number: 2,
        question: "Where did you hear about this event?",
        type: "options",
        answer: "",
        multipleAllowed: true,
        options: ["Linkedin", "Facebook", "Twitter", "Instagram"],
      },
    ],
  },
  {
    name: "Event Seven",
    by: "ajdih",
    area: "Lower Manhattan",
    day: "Monday",
    date: "Nov,13 2023",
    scheduledTime: "10:00 AM - 11:00 PM",
    image:
      "https://images.unsplash.com/photo-1492684223066-81342ee5ff30?q=80&w=1170&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
    details:
      "Details for Event SevenDetails forDetails forDetails forDetails forDetails forDetails forDetails forDetails forDetails forDetails forDetails forDetails for",
    price: "29.99",
    ticketsLeft: "120",
    address: "9012 Ocean Ave, Anytown, CA",
    questions: [
      {
        number: 1,
        question: "Company/Organization:",
        type: "input",
        answer: "",
        multipleAllowed: false,
        options: [],
      },
      {
        number: 2,
        question: "Job Title:",
        type: "input",
        answer: "",
        multipleAllowed: false,
        options: [],
      },
      {
        number: 2,
        question: "Are you a student?",
        type: "options",
        answer: "",
        multipleAllowed: false,
        options: ["Yes", "No"],
      },
      {
        number: 2,
        question: "Where did you hear about this event?",
        type: "options",
        answer: "",
        multipleAllowed: true,
        options: ["Linkedin", "Facebook", "Twitter", "Instagram"],
      },
    ],
  },
  {
    name: "Event Eight",
    by: "ajdih",
    area: "Lower Manhattan",
    day: "Monday",
    date: "Nov,13 2023",
    scheduledTime: "10:00 AM - 11:00 PM",
    image:
      "https://images.unsplash.com/photo-1492684223066-81342ee5ff30?q=80&w=1170&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
    details:
      "Details for Event EightDetails forDetails forDetails forDetails forDetails forDetails forDetails forDetails forDetails forDetails for",
    price: "Free",
    ticketsLeft: "N/A",
    address: "3456 Sunset Dr, Anytown, CA",
    questions: [
      {
        number: 1,
        question: "Company/Organization:",
        type: "input",
        answer: "",
        multipleAllowed: false,
        options: [],
      },
      {
        number: 2,
        question: "Job Title:",
        type: "input",
        answer: "",
        multipleAllowed: false,
        options: [],
      },
      {
        number: 2,
        question: "Are you a student?",
        type: "options",
        answer: "",
        multipleAllowed: false,
        options: ["Yes", "No"],
      },
      {
        number: 2,
        question: "Where did you hear about this event?",
        type: "options",
        answer: "",
        multipleAllowed: true,
        options: ["Linkedin", "Facebook", "Twitter", "Instagram"],
      },
    ],
  },
  {
    name: "Event Nine",
    by: "ajdih",
    area: "Lower Manhattan",
    day: "Monday",
    date: "Nov,13 2023",
    scheduledTime: "10:00 AM - 11:00 PM",
    image:
      "https://images.unsplash.com/photo-1492684223066-81342ee5ff30?q=80&w=1170&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
    details:
      "Details for Event NineDetails forDetails forDetails forDetails forDetails forDetails forDetails forDetails forDetails forDetails forDetails for",
    price: "18.00",
    ticketsLeft: "30",
    address: "7890 Hilltop Ln, Anytown, CA",
    questions: [
      {
        number: 1,
        question: "Company/Organization:",
        type: "input",
        answer: "",
        multipleAllowed: false,
        options: [],
      },
      {
        number: 2,
        question: "Job Title:",
        type: "input",
        answer: "",
        multipleAllowed: false,
        options: [],
      },
      {
        number: 2,
        question: "Are you a student?",
        type: "options",
        answer: "",
        multipleAllowed: false,
        options: ["Yes", "No"],
      },
      {
        number: 2,
        question: "Where did you hear about this event?",
        type: "options",
        answer: "",
        multipleAllowed: true,
        options: ["Linkedin", "Facebook", "Twitter", "Instagram"],
      },
    ],
  },
  {
    name: "Event Ten",
    by: "ajdih",
    area: "Lower Manhattan",
    image:
      "ihttps://images.unsplash.com/photo-1492684223066-81342ee5ff30?q=80&w=1170&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
    details:
      "Details for Event TenDetails forDetails forDetails forDetails forDetails forDetails forDetails forDetails forDetails forDetails forDetails for",
    price: "45.75",
    ticketsLeft: "Limited",
    address: "12345 Park Ave, Anytown, CA",
    questions: [
      {
        number: 1,
        question: "Company/Organization:",
        type: "input",
        answer: "",
        multipleAllowed: false,
        options: [],
      },
      {
        number: 2,
        question: "Job Title:",
        type: "input",
        answer: "",
        multipleAllowed: false,
        options: [],
      },
      {
        number: 2,
        question: "Are you a student?",
        type: "options",
        answer: "",
        multipleAllowed: false,
        options: ["Yes", "No"],
      },
      {
        number: 2,
        question: "Where did you hear about this event?",
        type: "options",
        answer: "",
        multipleAllowed: true,
        options: ["Linkedin", "Facebook", "Twitter", "Instagram"],
      },
    ],
  },
];
export const fetchEventsApi = async () => {
  try {
    // const response = await axios.get(API_URL);
    // return response.data; // Assuming your API returns an array of events

    return events;
  } catch (error) {
    console.error("Error fetching events:", error);
    return []; // Handle errors gracefully, e.g., return an empty array or throw an error
  }
};
